sudo: required
dist: trusty
services:
  - docker

language: go

go:
  - 1.9.4

python:
  - 3.5
  - 3.6 
  
matrix: 
  - include:
      - python: 3.7
        sudo: required
        dist: xenial
        
os:
  - linux
  - osx

env:
  matrix:
    - TARGETS="check"
    - TARGETS="testsuite"

  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - umask 022
  # Redo the travis setup but with the elastic/libbeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/GoogleCloudPlatform/pubsubbeat/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/GoogleCloudPlatform/pubsubbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/GoogleCloudPlatform/pubsubbeat/
  - cd $HOME/gopath/src/github.com/GoogleCloudPlatform/pubsubbeat/

install:
  - true

script:
  - make $TARGETS

after_success:
  # Copy full.cov to coverage.txt because codecov.io requires this file
